export enum ErrorCode {
  DB_ERROR = "DB_ERROR",
  WEB3_ERROR = "WEB3_ERROR",
  INVALID_DATA = "INVALID_DATA",
  CORRUPTED_DATA = "CORRUPTED_DATA",
}

export enum LicenseTypes {
  PERPETUAL = "PERPETUAL",
  SUBSCRIPTION = "SUBSCRIPTION",
}

export enum RejectCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
}
