AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  management-system-api

  Sample SAM Template for management-system-api

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: lib/hello-world/hello-world.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get

  LicenseDeployFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: lib/api-handlers/license/deploy.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        LicenseDeploy:
          Type: Api
          Properties:
            Path: /deploy
            Method: post

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
